name: nerf
description: A deployment toolkit providing CLI helpers to upload to testflight, appstore, playconsole, (similar to Fastlane)
version: 0.0.1-alpha
repository: https://github.com/evaisse/dart_nerf

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
